const ES = {
    TournamentBracktes: 'Tournament Grid',
    AllMatches: 'All matches',
    HistoryOfRates: 'History of rates',
    Settings: 'Settings',
    Group: 'Groups',
    MatchSchedule: 'Match schedule',
    P1: 'P1',
    P2: 'P2',
    bid: 'Bid',
    sound: 'Sound',
    vibration: 'Vibration',
    on: 'ON',
    off: 'OFF',
    TournamentTable: 'Tournament Table',
    MatchDetails: 'More about the match',
    TeamLineup1: 'Team line-up 1',
    TeamLineup2: 'Team line-up 2',
    No: 'No.',
    player: 'Player',
    Role: 'Role',
    DOB: 'DOB',
    Height: 'Height',
    Weight: 'Weight',
    Loading: 'Loading...',
    availableBalance: 'Available Balance',
    betAmount: 'Bet Amount',
    close: 'Close',
    bet: 'Bet',
}

const RS = {
    TournamentBracktes: 'Турнирная сетка',
    AllMatches: 'Все матчи',
    HistoryOfRates: 'История ставок',
    Settings: 'Настройки',
    Group: 'Группа',
    MatchSchedule: 'Расписание матчей',
    P1: 'П1',
    P2: 'П2',
    bid: 'Ставка',
    sound: 'Звук',
    vibration: 'Вибрация',
    on: 'ВКЛ',
    off: 'ВЫКЛ',
    TournamentTable: 'Турнирная таблица',
    MatchDetails: 'Подробнее о матче',
    TeamLineup1: 'Состав команды 1',
    TeamLineup2: 'Состав команды 2',
    No: '№',
    player: 'Игрок',
    Role: 'Амплуа',
    DOB: 'ДР',
    Height: 'Рост',
    Weight: 'Вес',
    Loading: 'Загрузка...',
    availableBalance: 'доступные средства',
    betAmount: 'Сумма ставки',
    close: 'Закрыть',
    bet: 'Сделать ставку',
}

export default RS;