export default {
    FireWorks: require('./fireworks.png'),
    Trophy: require('./trophy.png'),
    Football: require('./football.png'),
    AppLogo: require('./app_logo.png'),
    TournamentBrackets: require('./tournament_bracket.png'),
    AllMetches: require('./all_matches.png'),
    HistoryOfRates: require('./history_of_rates.png'),
    Settings: require('./settings.png'),
    BackIcon: require('./ic_back.png'),
    HorizonLine: require('./horizon_line.png'),
    FlagDemo: require('./flag_demo.png'),
    HalfFootball: require('./half_golden_foodball.png'),
    Coin: require('./ic_coin.png'),
    DownArrow: require('./ic_down_arrow.png'),
    UpArrow: require('./ic_up_arrow.png'),

    //Flags
    argentina: require('./flags/Argentina.png'),
    australia: require('./flags/Australia.png'),
    belgium: require('./flags/Belgium.png'),
    brazil: require('./flags/Brazil.png'),
    cameroon: require('./flags/Cameroon.png'),
    canada: require('./flags/Canada.png'),
    costa_rica: require('./flags/Costa_Rica.png'),
    croatia: require('./flags/Croatia.png'),
    denmark: require('./flags/Denmark.png'),
    ecuador: require('./flags/Ecuador.png'),
    england: require('./flags/England.png'),
    france: require('./flags/France.png'),
    germany: require('./flags/Germany.png'),
    ghana: require('./flags/Ghana.png'),
    ir_iran: require('./flags/IR_Iran.png'),
    japan: require('./flags/Japan.png'),
    korea_republic: require('./flags/Korea_Republic.png'),
    mexico: require('./flags/Mexico.png'),
    morocco: require('./flags/Morocco.png'),
    netherlands: require('./flags/Netherlands.png'),
    poland: require('./flags/Poland.png'),
    portugal: require('./flags/Portugal.png'),
    qatar: require('./flags/Qatar.png'),
    saudi_arabia: require('./flags/Saudi_Arabia.png'),
    senegal: require('./flags/Senegal.png'),
    serbia: require('./flags/Serbia.png'),
    spain: require('./flags/Spain.png'),
    switzerland: require('./flags/Switzerland.png'),
    tunisia: require('./flags/Tunisia.png'),
    uruguay: require('./flags/Uruguay.png'),
    usa: require('./flags/USA.png'),
    wales: require('./flags/Wales.png'),
    no_flag: require('./flags/No_Flag.png'),

}